# Site settings
title: 猫眼android
header-img: "img/bg_starbuck2.jpg"
tagline: "猫眼电影"
description: "在遙遠的地方 一切虔誠終必相遇"
baseurl: ""
url: "http://maoyanxuexi.github.io"
#url: "http://localhost:4000"

# About/contact
owner:
  name: "猫眼Android"
  email: maoyanxuexi@gmail.com
  bio: "明朝即長路 惜取此時心"

# Data
gavatar: http://oacl4nhb6.bkt.clouddn.com/icon_maoyan.jpg
favicon: img/favicon.ico

douban_username: maoyan
twitter_username: maoyan
github_username: maoyanxuexi
facebook_username: maoyan
weibo_username: maoyan
zhihu_username: maoyan

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "MYAndroid"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : maoyanxuexi
  disqus :
      short_name : maoyanxuexi

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation